name = "ayurveda-clinic"
compatibility_date = "2025-12-17"
pages_build_output_dir = "./dist"
account_id = "df062639da601bcc1a52d074c1a2be12"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ayurveda-db-prod"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"
